In [112]:
from __future__ import division
import pandas as pd
import numpy as np
import sklearn as sk

data = pd.read_csv('StudentLoanSimulatedData.csv')

# vars[0] is % of ParentsIncome dedicated to all of their children's educations
# vars[1] is # of hours worked by student per year
# vars[2] is education baseline (must be > 0)
# vars[3] is impact of grades on scholarship
# vars[4] is the negative impact of ParentsIncome on scholarship eligibility
vars = np.array([.15, 2000, 1, .25, .1])
N = 1000

def studentLoanData(vars,N):

    randMat = np.array(np.random.uniform(0,1,[N,20]))
    ParentsIncome = randMat[:,0]*100000
    NumberOfSiblings = np.floor(randMat[:,1]*10)
    ParentsPortion = np.divide(ParentsIncome*vars[0],1+NumberOfSiblings)

    WorkExperience = np.floor(randMat[:,2]*8)
    Education = np.floor(randMat[:,3]*2)
    Skills = np.floor(randMat[:,4]*4)
    MinimumWage = np.floor(randMat[:,5]*20)
    StudentIncome = vars[1]*MinimumWage+np.multiply(WorkExperience,Education+vars[2],Skills)

    Years = np.floor(randMat[:,6]*8)
    College = randMat[:,7]*10000
    InState = np.floor(randMat[:,8]*2)
    Tuition = np.multiply(Years,College,InState+1)

    Grades =  np.floor(randMat[:,9]*40)/10
    Scholarship = np.multiply(vars[3]*Grades,Tuition - vars[4]*ParentsIncome)
    Scholarship = Scholarship.clip(0)

    State = randMat[:,10]*15000
    Roomies = np.floor(randMat[:,11]*10)
    BlingFactor = np.floor(randMat[:,12]*9)
    LivingExpenses = np.divide(np.multiply(State,1+BlingFactor),1+Roomies)

    Materials = randMat[:,13]*5000

    StudentLoanAmount = ParentsPortion + StudentIncome + Scholarship - Tuition - LivingExpenses - Materials
    Loans = (StudentLoanAmount<0)
    Loans = Loans.astype(int)

    NumberOfSiblings
    StudentIncome

    data = pd.DataFrame.from_items([('Loans', Loans), ('ParentsIncome', ParentsIncome), 
                                    ('WorkExperience', WorkExperience), ('Education', Education), 
                                    ('MinimumWage', MinimumWage), ('Grades', Grades), 
                                    ('Tuition', Tuition), ('Years', Years), ('College', College), 
                                    ('InState', InState), ('BlingFactor', BlingFactor), 
                                    ('NumberOfSiblings', NumberOfSiblings), ('State', State), ('Materials', Materials)])

    return data

def histogramClass(data, testratio = .2, maxgrid = 2):
    if (str(type(data)) == "<class 'pandas.core.frame.DataFrame'>"):
        nrow= np.shape(data)[0]
        ncol = np.shape(data)[1]
        stop = int(np.ceil(nrow*(1-testratio)))
        testrow = int(nrow - stop)
        classifier = pd.DataFrame()
        bins = np.arange(0,1, 1/maxgrid)

        ##### Create grid lines
        for i in range(ncol):
            colmin = min(data.ix[:,i])
            colmax = max(data.ix[:,i])
            data.ix[:,i] = (data.ix[:,i]-colmin)/colmax

            if i>0:
                data.ix[:,i] = np.digitize(data.ix[:,i],bins)
            else:
                data.ix[:,i] = data.ix[:,i]

        histogram = data.loc[range(stop)]
        histogram2 = data.loc[range(stop+1, nrow)]
        
        
        
        ##### Store rows of histogram that predict "output = 1"
        vector = histogram.groupby(list(histogram.columns)[1:]).mean() >= .5
        a = vector.index.unique()
        classifier = dict()
        for i in a:
            classifier[i] = vector.ix[i]['Loans']

        count = 0
        results = np.zeros((testrow,1))
        
        for i in range(stop+1,nrow):
            if classifier.has_key(tuple(histogram2.loc[i][1:])):
            #if tuple(histogram2.ix[i,1:]) in classifier.keys():
                results[i-(stop+1)] = int(classifier[tuple(histogram2.loc[i][1:])])
            else:
                results[i-(stop+1)] = 0
            if results[i-(stop+1)] == histogram2.loc[i][0]:
                count = count + 1
        
        accuracy = (count/testrow)
        return accuracy
        
    else:
        print "Incorrect Data Type - Data should be in Pandas DataFrame."

In [126]:
for i in [10,100,1000,10000,100000,1000000]:
    data = studentLoanData(vars,i)
    acc = histogramClass(data)
    print str(i).ljust(10) + str(acc).ljust(10) + '\n'

0.0
10        0.0

0.6
100       0.6

0.525
1000      0.525

0.6865
10000     0.6865

0.78605
100000    0.78605

0.797245
1000000   0.797245

In [127]:
for i in [10,100,1000,10000,100000,1000000]:
    data = studentLoanData(vars,i)
    acc = histogramClass(data, maxgrid = 3)
    print str(i).ljust(10) + str(acc).ljust(10) + '\n'

0.0
10        0.0

0.45
100       0.45

0.495
1000      0.495

0.492
10000     0.492

0.56455
100000    0.56455

0.771705
1000000   0.771705

In [66]:
vec.ix[a[2]]['Loans']

True

In [6]:
h1.groupby(list(h1.columns[1:])).mean()

                                                                                                                                         Loans
ParentsIncome WorkExperience Education MinimumWage Grades Tuition Years College InState BlingFactor NumberOfSiblings State Materials
1             1              1         1           1      1       1     1       1       1           1                1     1          0.428571
                                                                                                                           2          0.187500
                                                                                                                     2     1          0.409091
                                                                                                                           2          0.636364
                                                                                                    2                1     1          0.500000
                                                                                                                           2          0.352941
                                                                                                                     2     1          0.652174
                                                                                                                           2          0.600000
                                                                                        2           1                1     1          0.571429
                                                                                                                           2          0.571429
                                                                                                                     2     1          0.821429
                                                                                                                           2          0.666667
                                                                                                    2                1     1          0.777778
                                                                                                                           2          0.666667
                                                                                                                     2     1          0.888889
                                                                                                                           2          0.869565
                                                                                2       1           1                1     1          0.384615
                                                                                                                           2          0.428571
                                                                                                                     2     1          0.590909
                                                                                                                           2          0.555556
                                                                                                    2                1     1          0.333333
                                                                                                                           2          0.461538
                                                                                                                     2     1          0.736842
                                                                                                                           2          0.724138
                                                                                        2           1                1     1          0.631579
                                                                                                                           2          0.380952
                                                                                                                     2     1          0.869565
                                                                                                                           2          0.888889
                                                                                                    2                1     1          0.541667
                                                                                                                           2          0.647059
...                                                                                                                                        ...
2             2              2         2           2      2       2     2       1       1           1                2     1          0.200000
                                                                                                                           2          0.153846
                                                                                                    2                1     1          0.222222
                                                                                                                           2          0.157895
                                                                                                                     2     1          0.090909
                                                                                                                           2          0.333333
                                                                                        2           1                1     1          0.000000
                                                                                                                           2          0.307692
                                                                                                                     2     1          0.250000
                                                                                                                           2          0.857143
                                                                                                    2                1     1          0.266667
                                                                                                                           2          0.583333
                                                                                                                     2     1          0.750000
                                                                                                                           2          0.687500
                                                                                2       1           1                1     1          0.100000
                                                                                                                           2          0.100000
                                                                                                                     2     1          0.200000
                                                                                                                           2          0.375000
                                                                                                    2                1     1          0.100000
                                                                                                                           2          0.400000
                                                                                                                     2     1          0.300000
                                                                                                                           2          0.545455
                                                                                        2           1                1     1          0.230769
                                                                                                                           2          0.187500
                                                                                                                     2     1          0.578947
                                                                                                                           2          0.571429
                                                                                                    2                1     1          0.090909
                                                                                                                           2          0.428571
                                                                                                                     2     1          0.846154
                                                                                                                           2          0.812500

[5118 rows x 1 columns]

In [74]:
from __future__ import division
import numpy as np
import pandas as pd

vars = np.array([.15, 2000, 1, .25, .1])
N = 10

randMat = np.array(np.random.uniform(0,1,[N,20]))
ParentsIncome = randMat[:,0]*100000
NumberOfSiblings = np.floor(randMat[:,1]*10)
ParentsPortion = np.divide(ParentsIncome*vars[0],1+NumberOfSiblings)

WorkExperience = np.floor(randMat[:,2]*8)
Education = np.floor(randMat[:,3]*2)
Skills = np.floor(randMat[:,4]*4)
MinimumWage = np.floor(randMat[:,5]*20)
StudentIncome = vars[1]*MinimumWage+np.multiply(WorkExperience,Education+vars[2],Skills)

Years = np.floor(randMat[:,6]*8)
College = randMat[:,7]*10000
InState = np.floor(randMat[:,8]*2)
Tuition = np.multiply(Years,College,InState+1)

Grades =  np.floor(randMat[:,9]*40)/10
Scholarship = np.multiply(vars[3]*Grades,Tuition - vars[4]*ParentsIncome)
Scholarship = Scholarship.clip(0)

State = randMat[:,10]*15000
Roomies = np.floor(randMat[:,11]*10)
BlingFactor = np.floor(randMat[:,12]*9)
LivingExpenses = np.divide(np.multiply(State,1+BlingFactor),1+Roomies)

Materials = randMat[:,13]*5000

StudentLoanAmount = ParentsPortion + StudentIncome + Scholarship - Tuition - LivingExpenses - Materials
Loans = (StudentLoanAmount<0)
Loans = Loans.astype(int)

NumberOfSiblings
StudentIncome

data = pd.DataFrame.from_items([('Loans', Loans), ('ParentsIncome', ParentsIncome), 
                                ('WorkExperience', WorkExperience), ('Education', Education), 
                                ('MinimumWage', MinimumWage), ('Grades', Grades), 
                                ('Tuition', Tuition), ('Years', Years), ('College', College), 
                                ('InState', InState), ('BlingFactor', BlingFactor), 
                                ('NumberOfSiblings', NumberOfSiblings), ('State', State), ('Materials', Materials)])
#data = pd.DataFrame(Loans,index = len(Loans),columns ="Loans")

In [75]:
type(Loans)
print type(Loans[0])
np.bincount(Loans)
data

<type 'numpy.int32'>

,Loans,ParentsIncome,WorkExperience,Education,MinimumWage,Grades,Tuition,Years,College,InState,BlingFactor,NumberOfSiblings,State,Materials
0,1,38208.199852,2,1,1,0.1,16877.499035,4,4219.374759,1,1,5,12778.830086,2196.416108
1,1,67866.672853,4,1,15,2.1,62702.776870,7,8957.539553,1,8,7,11161.854828,778.192687
2,1,14110.977646,0,1,19,1.2,39019.156628,6,6503.192771,0,5,3,9522.070619,2933.859108
3,0,39665.853916,1,1,16,1.6,1534.283291,1,1534.283291,1,0,2,2228.855057,2284.473613
4,1,60216.881642,4,0,4,1.6,4833.306568,6,805.551095,0,8,5,10549.180337,2456.709407
5,0,60925.425113,5,0,17,0.1,6583.304852,3,2194.434951,0,2,2,3713.481982,1993.600715
6,1,44187.609046,6,0,17,2.5,30033.005398,6,5005.500900,0,7,8,2783.966271,3207.276577
7,0,58670.005143,5,1,12,0.0,0.000000,0,5478.782599,0,6,4,3740.078524,2419.427152
8,0,78509.781715,6,1,14,1.7,6485.864231,7,926.552033,0,5,8,407.674644,1982.476717
9,1,21383.762820,3,0,4,1.3,22250.108256,4,5562.527064,1,1,3,11687.596886,3227.362958

In [70]:
#Troubleshooting array changes for Grades
#
#Compare the troublesome first line to the corrected second:
#Scholarship = np.multiply(vars[3],Grades,Tuition - vars[4]*ParentsIncome)
#Scholarship = np.multiply(vars[3]*Grades,Tuition - vars[4]*ParentsIncome)
#The first line changes the Grades array to equal the Scholarship array.

Grades =  np.floor(randMat[:,9]*40)/10
print vars[3]
print Grades
var1 = vars[3]*Grades
print ""

print vars[4]
print ParentsIncome
print Tuition
var2 = Tuition - vars[4]*ParentsIncome
print ""

Scholarship = np.multiply(var1,var2)
print Scholarship
Scholarship = np.multiply(vars[3]*Grades,Tuition - vars[4]*ParentsIncome)
print Scholarship
print Grades

print np.corrcoef(Scholarship,Grades)
print np.corrcoef(Scholarship,Tuition)
print np.corrcoef(Scholarship,ParentsIncome)

0.25
[ 0.7  1.9  2.2  2.   2.   3.5  0.6  0.6  3.8  0.2]

0.1
[ 70291.34892352  24287.34786823  94510.44681296  79524.55773913
  34623.79290463  46053.82643722  42569.0633275    2050.34557395
  15798.91178017  19323.73437017]
[     0.              0.          40046.03682264    160.25678846
   8239.148146        0.          25474.08143788  26516.29533332
  36443.23653981  15154.13956315]

[ -1230.09860616  -1153.64902374  16827.24567774  -3896.09949273
   2388.38442777  -4029.70981326   3182.57626577   3946.68911639
  33120.1780937     661.08830631]
[ -1230.09860616  -1153.64902374  16827.24567774  -3896.09949273
   2388.38442777  -4029.70981326   3182.57626577   3946.68911639
  33120.1780937     661.08830631]
[ 0.7  1.9  2.2  2.   2.   3.5  0.6  0.6  3.8  0.2]
[[ 1.          0.46671938]
 [ 0.46671938  1.        ]]
[[ 1.          0.81152663]
 [ 0.81152663  1.        ]]
[[ 1.         -0.12634877]
 [-0.12634877  1.        ]]